# Generated by Django 5.1.1 on 2024-09-22 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.IntegerField(default=2024)),
                ('units_used', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField(default=1500)),
                ('total_amount', models.PositiveIntegerField(editable=False)),
                ('control_number', models.PositiveIntegerField(default='0620709539')),
                ('status', models.CharField(choices=[('NOT PAID', 'Not Paid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='NOT PAID', max_length=10)),
                ('payment_verification_message', models.TextField(blank=True, null=True)),
                ('payment_verification_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bills_as_customer', to=settings.AUTH_USER_MODEL)),
                ('service_provider', models.ForeignKey(limit_choices_to={'is_serviceprovider': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bills_as_service_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.PositiveIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
            ],
        ),
    ]
